import {NextIntlClientProvider} from 'next-intl';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { Roboto } from 'next/font/google';
import theme from "../theme";
import { getLocale } from 'next-intl/server';
const rtlLocales = ['ar', 'he', 'fa', 'ur'];
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto'
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,params }) {
var { locale } = await params;
if (!locale) locale = await getLocale();
const direction = rtlLocales.includes(locale) ? 'rtl' : 'ltr';
console.log('locale',locale)
  return (
    <html lang={locale} dir={direction}>
      <body
        style={{overflowX:"hidden"}}
        className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AppRouterCacheProvider>
            <NextIntlClientProvider>
              <ThemeProvider theme={theme}>{children}</ThemeProvider>
            </NextIntlClientProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
